[package]
name = "AdventOfCode2021"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.0"
bitflags = "1.3.2"
itertools = "0.10.3"
bitvec = "0.22.3"
hex = "0.4.3"
rayon = "1.5.1"
dashmap = { version = "5.0.0", features = ["rayon"] }